				<div class="content-text">
                	<h3>Industrial Estate</h3><br>
                    <img src="./images/Industrial-Estate.jpg"/><br><br>
                    <p>Bangladesh Government is making all-out efforts to industrialise the country with a view to create new employment opportunity and to develop the socio-economic condition of the country. Industrial development is not possible without enthusiastic and solvent entrepreneurs/financiers. Further, entrepreneurs cannot establish their industries if suitable land with all the required infrastructural facilities such as road, gas, electricity, water supply are not available. To accomplish these needs, the Government of Bangladesh has developed Industrial estates through different agencies namely-Bangladesh Small and Cottage Industries Corporation (BSCIC), Bangladesh Export Processing Zone Authority (BEPZA), etc. Sometimes, Government also acquires land for setting up industries as per request of the sponsors/entrepreneurs. But, this practice is rare and time consuming. Most of the prospective entrepreneurs want to establish their industrial units in and around Dhaka Metropolitan City to take the advantage of its well developed infrastructural facilities as well as the large market for their products; but the industrial estates of Tejgaon and Tongi have already been over-crowded and over-capacitated. Moreover, there is hardly any scope of expanding those estates due to non-availability of land in the surrounding areas.</p>
                    <br>
                    <br />
                    <p>The SAARC INDUSTRIAL ESTATE is established with the idea of relieving all those troubles and bottlenecks by developing a favourable atmosphere for the prospective entrepreneurs.</p>
                    <br />
                    <p>The site for SAARC INDUSTRIES ESTATE has been selected in the heart of Sonargaon Upazilla. The site is within the Master plan of greater Dhaka Metropolitan city. The main aim is to extend package deal services to the entrepreneurs of the SAARC countries by providing all logistic supports under one roof.</p>
                    <br />
                    <p>An investor in SAARC INDUSTRIAL ESTATE has a 140 million consumer's market in Bangladesh accessible by road, sea and air. In addition, the SAARC and other South East Asian countries provide a potential market of more than 2 billion people. The total project of the SAARC INDUSTRIAL ESTATE is estimated to cover 150 acres of  land of which initially an area of 60 acres will be isolated for industrialisation. In the first phase, 25 acres has been taken up for developm ent with all infrastructural facilities, fully suitable for setting up industries by the entrepreneurs. The Total Project area will be developed in phases.</p>
                    <br />
                    <p>The 25 acres of land will be divided into 150 plots covering 15-20 decimals. Entrepreneurs can purchase one or more plots according to their needs.</p>
                </div>