				<div class="content-text">
                	<h3>Land Division</h3><br>
                    <p>
                        East, West, North, South, New and Islami Towns are unique projects of BDC to meet the acute housing crisis by building satellite towns which will meet not only  needs but also provide all other facilities that are required for modern living. These towns will provide the desired housing facilities for about 0.10 million dwellers in seven localities. On providing all modern amenities and utilities like gas, electricity and water the land plots are made available at a very reasonable instalments. Apart from the residential accommodation the towns will also have public transportation system, which will link up the satellite towns with the mega city.
                    </p>
                    <br>
                    <p>Total area of land in Bangladesh is 57126 sq. miles. Administratively it has been divided into six Divisions,  which are subdivided in total 64 Zillas. All these Zillas are interconnected through well-designed metal road networks known as : "National Highway". One interesting feature of these Zillas is that the main town or business activities have been developed around these National Highways. Keeping this view in consideration BANGLADESH DEVELOPMENT COMPANY LTD. (BDC) has come up with a unique proposal of developing Mini township beside these National Highway as well as at the entrance of each Zilla town. The size of each of these Township will be initially of 15-20 acres, of which 12 to 18 acres will be earmarked for residential use and the rest 2-3 acres will be developed for commercial use. In these commercial plots, BDC likes to provide a petrol pump with provisions for car servicing and emergency repair, fast food restaurant, rest house, public toilet facilities, pharmacy & clinic, departmental stores, generator house and mosque. The residential area will be targeted for middle class people. All civic amenities such as Electricity, Water, Sewerage, Gas (if available in locality), etc. will be provided here. These mini townships will be called "BDC TOWN".</p>
                    <br>
                    <p>The project includes a group of six storied buildings with plenty of greenery and space for children's play ground. Like all its apartment projects, BDC has given special emphasis to ensure sufficient natural light and ventilation for each apartment. In addition, there is common space for each building to accommodate shops, mosques, stores etc. With a growing middle class that has adopted the modern life style, the need for affordable "BDC" housing cannot be ignored.</p>
                </div>